### ISSUE TITLE
The Raku community is willing to take over this module if you wish

### ISSUE THREAD

**Issue by tbrowder** [raku-community-modules/Algorithm--Diff#20]
Raku users want to use this module but can't with its current status.

**Comment by Takadonet** [comment]
I am not planning doing anymore development of this module.
I would be happy that the community takes over the repo. 
How do you want to proceed?  We got lot of options.

**Comment by lizmat** [comment]
@Takadonet One option would be to transfer the repo to the raku-community-modules org.

If you have rights there, you can do that yourself.  If not, you could make me admin on this repo, and I can do the transfer for you.

The advantage of a transfer is that all issues / discussions remain

**Comment by lizmat** [comment]
@Takadonet I've given you privileges on raku-community-modules: you should be able to transfer this repo to it now

**Comment by Takadonet** [comment]
It has been transferred! 

Good luck.
